library(data.table)
library(plyr)
library(dplyr)
ytrain<-fread("train/y_train.txt")
xtrain<-fread("train/X_train.txt")
xtest<-fread("test/X_test.txt")
ytest<-fread("test/y_test.txt")
x<-bind_rows(xtrain,xtest)
y<-bind_rows(ytrain,ytest)
features<-fread("features.txt")
names(x)<-features$V2
names(y)<-"ActivityCode"
z<-cbind(y,x)
activitylabels<-fread("activity_labels.txt")
names(activitylabels)<-c("ActivityCode","ActivityDescription")
labelled<-join(activitylabels,z)
meancols<-grep("mean\\()",names(labelled))
stdcols<-grep("std\\()",names(labelled))
CleanData<-data.frame(subset(labelled,,sort(c(1,2,meancols,stdcols))))
Compact<-aggregate(CleanData[,-(1:2)],by=list(CleanData[,2]), mean)
print("Your data has been cleaned! It is called Compact")